type: horizontal-stack
cards:
  - type: button
    name: Vol Down
    tap_action:
      action: call-service
      service: esphome.denon_receiver_volume_down
    icon: 'mdi:volume-minus'
  - type: button
    name: Vol Up
    tap_action:
      action: call-service
      service: esphome.denon_receiver_volume_up
    icon: 'mdi:volume-plus'
    entity: switch.denon
  - type: button
    name: Mute
    tap_action:
      action: call-service
      service: esphome.denon_receiver_mute
    icon: 'mdi:volume-mute'
